### ISSUE TITLE
路径怎么写

### ISSUE THREAD

**Issue by jth445600** [jiajiajia343434/picgo-plugin-nextcloud-uploader#2]
![image](https://user-images.githubusercontent.com/24479489/77152988-dcc5b200-6a90-11ea-8a00-a63f503d83d6.png)
这样是不行的

**Comment by jiajiajia343434** [comment]
根目录的话保存路径这个别填就是根目录，目前程序逻辑比较简单，没处理'/'的情况

**Comment by jiajiajia343434** [comment]
刚试了下，这样是可以的啊，是不是你别的配置有什么问题
![image](https://user-images.githubusercontent.com/7382615/77271200-05e07f80-6ce9-11ea-888b-b8dd4636f842.png)

**Comment by jth445600** [comment]
我发现个问题，host填的是域名啊，我填的是webdex什么的域名

**Comment by jth445600** [comment]
@jiajiajia343434

**Comment by jth445600** [comment]
还有就是，用这个方式不支持文件名中存在中文

**Comment by jiajiajia343434** [comment]
中文是有点问题，我修复一下，不过文件名我一般是用PicGo生成的时间戳，你自己制定名字的话，有可能会把已有的文件覆盖。。host就是填nextcloud服务的地址
