### ISSUE TITLE
难受

### ISSUE THREAD

**Issue by chineseMYC** [jiajiajia343434/picgo-plugin-nextcloud-uploader#3]
这个只能写域名吗        我填的ip:端口    疯狂失败

![image](https://user-images.githubusercontent.com/49779026/84825214-b09bdc00-b053-11ea-94f8-322f3a2c6409.png)
不是我的问题吧

**Comment by jiajiajia343434** [comment]
不是吧，ip也可以，我自己是这么用的没啥问题
host: http://ip:port
user: user
password: password
path: /public
