### ISSUE TITLE
使用docker版nextcloud：20，上传文件，提示路径不存在

### ISSUE THREAD

**Issue by zxjt777** [jiajiajia343434/picgo-plugin-nextcloud-uploader#6]
在使用docker版nextcloud：20，在上传图片时，日志显示提交的路径为：PUT  /remote.php/dav/files/user/path/年/月/日/文件。而在上传文件时，并不会在path路径下创建/年/月/日的文件夹，提示路径不存在，如果创建上出目录则能够成功。建议将其修改成年-月-日-秒-文件.文件名的格式。

**Comment by jiajiajia343434** [comment]
> ```
>  在使用docker版nextcloud：20，在上传图片时，日志显示提交的路径为：PUT  /remote.php/dav/files/user/path/年/月/日/文件。而在上传文件时，并不会在path路径下创建/年/月/日的文件夹，提示路径不存在，如果创建上出目录则能够成功。建议将其修改成年-月-日-秒-文件.文件名的格式。
> ```

什么情况会有这种形式的文件名啊？是不是跟你使用PicGo的其他插件有关？

**Comment by zxjt777** [comment]
> > ```
> >  在使用docker版nextcloud：20，在上传图片时，日志显示提交的路径为：PUT  /remote.php/dav/files/user/path/年/月/日/文件。而在上传文件时，并不会在path路径下创建/年/月/日的文件夹，提示路径不存在，如果创建上出目录则能够成功。建议将其修改成年-月-日-秒-文件.文件名的格式。
> > ```
> 
> 什么情况会有这种形式的文件名啊？是不是跟你使用PicGo的其他插件有关？

比如今天上午上传a.jpg，日志显示的就是 PUT  /remote.php/dav/files/user/path/2021/01/04/a.jpg 提示路径不正确。 但是晚上测试的时候又可以了。我在查查。

**Comment by zxjt777** [comment]
> > > ```
> > >  在使用docker版nextcloud：20，在上传图片时，日志显示提交的路径为：PUT  /remote.php/dav/files/user/path/年/月/日/文件。而在上传文件时，并不会在path路径下创建/年/月/日的文件夹，提示路径不存在，如果创建上出目录则能够成功。建议将其修改成年-月-日-秒-文件.文件名的格式。
> > > ```
> > 
> > 
> > 什么情况会有这种形式的文件名啊？是不是跟你使用PicGo的其他插件有关？
> 
> 比如今天上午上传a.jpg，日志显示的就是 PUT /remote.php/dav/files/user/path/2021/01/04/a.jpg 提示路径不正确。 但是晚上测试的时候又可以了。我在查查。

可能和时区有关，将docker运行的nextcloud设置时区后，就没有问题了，很奇怪。
