### ISSUE TITLE
中文path會無法上傳

### ISSUE THREAD

**Issue by dhtw** [jiajiajia343434/picgo-plugin-nextcloud-uploader#7]
應修改如下才能正常上傳到中文路徑

url: `${host}/remote.php/dav/files/${user}/${path}/${encodeURI(image.fileName)}`,
改為
url: `${host}/remote.php/dav/files/${user}/${encodeURI(path)}/${encodeURI(image.fileName)}`,
![image](https://user-images.githubusercontent.com/81405086/112589875-d228c000-8e3c-11eb-8199-5fd378ec0ccf.png)

url: `${host}/remote.php/dav/files/${user}/${path}/${encodeURI(image.fileName)}`,
改為
url: `${host}/remote.php/dav/files/${user}/${encodeURI(path)}/${encodeURI(image.fileName)}`,
![image](https://user-images.githubusercontent.com/81405086/112589944-ee2c6180-8e3c-11eb-9e7f-44b888a0cbb3.png)

**Comment by jiajiajia343434** [comment]
感谢您的建议
